Update the README.md file to describe the repo.
aliu917/step-projects pull request #1
Opened 2020-05-26 17:12 UTC by aliu917

I updated the readme as the prompts instructed.

2020-05-26 23:54 UTC, dibenede requested changes
I recommend keeping the commit message as descriptive as possible. Git typically uses the first 80 characters before a newline as the brief message that will show up in the short commit log. You can then expand on it for the extended history view. So, for this change, I would do something like:

Add and format data about me (I think that's less than 80)

* Add a summary about me.
* Make information about my hobbies available on click.
* Add basic formatting.

2020-05-26 23:54 UTC, dibenede commented on portfolio/src/main/webapp/script.js
>  function addRandomGreeting() {
Rename greeting -> fact here and below

2020-05-26 23:57 UTC, dibenede approved these changes

2020-05-26 23:57 UTC, dibenede commented on portfolio/src/main/webapp/index.html
> -      <p></p>
optional: I think you can just do ```<p />``` for things like this

2020-05-27 16:48 UTC, dibenede approved these changes

2020-05-27 17:34 UTC, aliu917 commented
A question about the commit messages: are you saying that each commit should contain the change I made for that commit in the first line and then bullet points for all the previous commit messages I made? So like for my most recent commit about adding a project section, it would be:
Finished the project section

- changed design and formatting
- add a summary about me
- add basic formatting
- make information about hobbies available on click

2020-05-27 18:17 UTC, dibenede commented
> A question about the commit messages: are you saying that each commit should contain the change I made for that commit in the first line and then bullet points for all the previous commit messages I made? So like for my most raecent commit about adding a project section, it would be:
> Finished the project section
> 
> * changed design and formatting
> * add a summary about me
> * add basic formatting
> * make information about hobbies available on click

No, sorry. I may have put my comment in a weird spot. Basically your first line should be a summary. If you have a small commit, the summary may be sufficient to describe what you did and you can call it good.

If you have a large commit, then it's a good idea to list out what's included in it. Sorry for the confusion.

2020-05-27 23:49 UTC, merged